package Converter;


/**
* Converter/Conversion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Converter.idl
* Thursday, December 21, 2023 9:14:32 PM WET
*/

public interface Conversion extends ConversionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Conversion
