package Converter;


/**
* Converter/ConversionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Converter.idl
* Thursday, December 21, 2023 9:14:32 PM WET
*/

public interface ConversionOperations 
{
  String convertNumber (String number, short sourceBase, short targetBase);
} // interface ConversionOperations
