package Converter;


/**
* Converter/ConversionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from converter.idl
* Saturday, December 23, 2023 8:12:58 PM WET
*/

abstract public class ConversionHelper
{
  private static String  _id = "IDL:Converter/Conversion:1.0";

  public static void insert (org.omg.CORBA.Any a, Converter.Conversion that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Converter.Conversion extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Converter.ConversionHelper.id (), "Conversion");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Converter.Conversion read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ConversionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Converter.Conversion value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Converter.Conversion narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Converter.Conversion)
      return (Converter.Conversion)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Converter._ConversionStub stub = new Converter._ConversionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Converter.Conversion unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Converter.Conversion)
      return (Converter.Conversion)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Converter._ConversionStub stub = new Converter._ConversionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
