package Converter;

/**
* Converter/ConversionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from converter.idl
* Saturday, December 23, 2023 8:12:58 PM WET
*/

public final class ConversionHolder implements org.omg.CORBA.portable.Streamable
{
  public Converter.Conversion value = null;

  public ConversionHolder ()
  {
  }

  public ConversionHolder (Converter.Conversion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Converter.ConversionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Converter.ConversionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Converter.ConversionHelper.type ();
  }

}
