package Converter;


/**
* Converter/ConversionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from converter.idl
* Saturday, December 23, 2023 8:12:58 PM WET
*/

public interface ConversionOperations 
{
  String convertNumber (String number, short sourceBase, short targetBase);
} // interface ConversionOperations
